server:
  port: 8001

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.spcloud.dwcode.payment8001.entity
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spcloud?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
